name       : xcb-util-keysyms
version    : 0.4.0
release    : 2
source     :
    - http://xcb.freedesktop.org/dist/xcb-util-keysyms-0.4.0.tar.bz2 : 0ef8490ff1dede52b7de533158547f8b454b241aa3e4dcca369507f66f216dd9
license    : custom
summary    : Utility libraries for XC Binding - Standard X key constants and conversion to/from keycodes
description: |
    Utility libraries for XC Binding - Standard X key constants and conversion to/from keycodes
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig(xcb)
component  : xorg.library
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
